version: '3.7'

services:
  # Postgres database container configuration
  db:
    container_name: postgres2
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/data/postgres
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge

volumes:
    db:

