package com.yaashall.bankapp.utils.accountutils;


/**
 * Class for validating account numbers generated by AccountNumberGenerator.
 *
 * @author Yassine CHALH
 */
public class AccountNumberValidator {

    /**
     * Validates an account number.
     *
     * The method verifies the account number format and the correctness of the check digit
     * using the Luhn Algorithm.
     *
     * @param accountNumber The account number to be validated.
     * @return true if the account number is valid, false otherwise.
     */
    public static boolean validateAccountNumber(String accountNumber) {
        if (accountNumber == null || accountNumber.length() != 11) {
            return false;
        }

        String numberWithoutCheckDigit = accountNumber.substring(0, accountNumber.length() - 1);
        int actualCheckDigit = Integer.parseInt(accountNumber.substring(accountNumber.length() - 1));

        int expectedCheckDigit = calculateLuhnCheckDigit(numberWithoutCheckDigit);

        return actualCheckDigit == expectedCheckDigit;
    }

    private static int calculateLuhnCheckDigit(String number) {
        int sum = 0;
        boolean alternate = false;

        for (int i = number.length() - 1; i >= 0; i--) {
            int n = Integer.parseInt(number.substring(i, i + 1));
            if (alternate) {
                n *= 2;
                if (n > 9) {
                    n -= 9;
                }
            }
            sum += n;
            alternate = !alternate;
        }

        return (10 - (sum % 10)) % 10;
    }
}
